<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var ListProduct $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Nvm\Wholesale\Block\Customer\Wholesale\ListProduct;

?>
<?php if ($block->getWholesales() && count($block->getWholesales())): ?>
    <div class="table-wrapper reviews">
        <table class="data table table-reviews" id="my-reviews-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Product Wholesales')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col description"><?= $escaper->escapeHtml(__('Customer Name')) ?></th>
                <th scope="col" class="col description"><?= $escaper->escapeHtml(__('Email')) ?></th>
                <th scope="col" class="col description"><?= $escaper->escapeHtml(__('Phone Number')) ?></th>
                <th scope="col" class="col item"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                <th scope="col" class="col description"><?= $escaper->escapeHtml(__('Message')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getWholesales() as $wholesale): ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Customer Name')) ?>" class="col description">
                        <?= $wholesale->getCustomerName() ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" class="col description">
                        <?= $wholesale->getCustomerEmail() ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>" class="col description">
                        <?= $wholesale->getCustomerPhone() ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?= $escaper->escapeUrl($block->getProductData($wholesale)->getProductUrl()) ?>">
                                <?= $escaper->escapeHtml($wholesale->getProductName()) ?>
                            </a>
                        </strong>
                    </td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Message')) ?>" class="col description">
                        <?= $wholesale->getCustomerMessage() ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $escaper->escapeUrl($block->getWholesaleUrl($wholesale)) ?>" class="action more">
                            <span><?= $escaper->escapeHtml(__('See Details')) ?></span>
                        </a>
                    </td>

                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('You have submitted no wholesale products.')) ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
