<?php
/** @var Nvm\Wholesale\Block\ContactWholesaleButton $block */
?>
<?php if ($block->compareAttributes()): ?>
    <button class="action primary wholesale-contact-button" type="button" id="contactWholesaleButton">
        Contact for Wholesale
    </button>
    <script>
        document.getElementById("contactWholesaleButton").addEventListener("click", function () {
            window.location.href = '<?php echo $block->getButtonUrl(); ?>';
        });
    </script>
<?php endif; ?>
